version: "3.8"

services:
  db:
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
    build:
      context: ./app
#      dockerfile: Dockerfile.dev
    ports:
      - 8888:8888
      - "2345:2345"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/go/src/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - "db"
